services:

  dfwebadmin:
    container_name: darkfactorweb_adminer
    image: adminer
    restart: always
    networks: 
      - net_dfweb_backend
    environment: 
      ADMINER_DEFAULT_SERVER: dfwebdb
    ports:
      - 4001:8080

  dfwebdb:
    image: mariadb:10.9
    container_name: darkfactorweb_database
    user: root
    restart: always
    networks: 
      - net_dfweb_backend
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=dfweb"
      - "MYSQL_USER=webuser"
      - "MYSQL_PASSWORD=secretpwd"
    volumes:
      - darkfactorweb-mariadb:/var/lib/mysql
      - ./database/darkfactorweb.sql:/darkfactorweb.sql
      #- ./database/createdb.sql:/createdb.sql
      #- ./database/my.cnf:/etc/my.cnf
    ports:
      - 4002:3306


  dfweb_bootstrap:
    container_name: darkfactorweb_web_bootstrap
    build:
      network: host
      context: ./
      dockerfile: ./DFWeb.FR.BootStrap/Dockerfile
      args:
        username: ${NUGET_USERNAME}
        token: ${NUGET_TOKEN}
      secrets:
        - nuget_username
        - nuget_token
    environment:
      - ASPNETCORE_ENVIRONMENT=DevelopmentDocker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "4000:80"
    networks:
      - net_dfweb_backend

  dfweb_tailwind:
    container_name: darkfactorweb_web_tailwind
    build:
      network: host
      context: ./
      dockerfile: ./DFWeb.FR.Tailwind/Dockerfile
      args:
        username: ${NUGET_USERNAME}
        token: ${NUGET_TOKEN}
      secrets:
        - nuget_username
        - nuget_token
    environment:
      - ASPNETCORE_ENVIRONMENT=DevelopmentDocker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "4005:80"
    networks:
      - net_dfweb_backend
    depends_on: 
      - dfwebdb

networks:
  net_dfweb_backend:
    name: dfweb_backend

volumes:
  # docker volume create darkfactorweb-mariadb
  darkfactorweb-mariadb:
    external: true  

secrets:
  nuget_username:
    environment: NUGET_USERNAME
  nuget_token:
    environment: NUGET_TOKEN