#
# Build Deploy file for Docker container
# Change the variables in this section to match your project
#

name: DFWeb Tailwind - Deploy

defaults:
  run:
    working-directory: .

on:
  release:
    types: [published]

  pull_request:
    types: [closed]
    branches: ["master", "main"]

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:

  staging:
    if: github.event.pull_request.merged == true || github.event.inputs.environment == 'staging' || github.event.inputs.environment == 'production'
    name: Deploy to Staging
    uses: DarkFactorAS/Infrastructure/.github/workflows/infrastructure-server-deploy.yml@v1.6
    with:
      environment: staging
      external_port: 4006
      project_name: "DFWeb.FR.Tailwind"
      dockerfile: "DFWeb.FR.Tailwind/Dockerfile"
      versionfile: "DFWeb.FR.Tailwind/Program.cs"
      config_path: "/DFWeb.FR.Tailwind"
    secrets: inherit

  production:
    if: github.event.pull_request.merged == true || github.event.inputs.environment == 'production' || github.event_name == 'release'
    name: Deploy to Production
    needs: [staging]
    uses: DarkFactorAS/Infrastructure/.github/workflows/infrastructure-server-deploy.yml@v1.6
    with:
      environment: production
      external_port: 4106
      project_name: "DFWeb.FR.Tailwind"
      dockerfile: "DFWeb.FR.Tailwind/Dockerfile"
      versionfile: "DFWeb.FR.Tailwind/Program.cs"
      config_path: "/DFWeb.FR.Tailwind"
    secrets: inherit

