#
# Build Deploy file for Docker container
# Change the variables in this section to match your project
#

name: DFWeb BootStrap - Deploy

defaults:
  run:
    working-directory: .

on:
  release:
    types: [published]

  pull_request:
    types: [closed]
    branches: ["master", "main"]

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

permissions:
  contents: read
  packages: read
  actions: write 

jobs:

  build-docker-image:
    if: github.event.pull_request.merged == true || github.event.inputs.environment == 'staging' || github.event.inputs.environment == 'production'
    name: Build Docker Image
    uses: ./.github/workflows/infrastructure-build-docker-image.yml
    with:
      project_name: "DFWeb.FR.BootStrap"
      dockerfile: "DFWeb.FR.BootStrap/Dockerfile"
      versionfile: "DFWeb.FR.BootStrap/Program.cs"
    secrets: inherit

  staging:
    if: github.event.pull_request.merged == true || github.event.inputs.environment == 'staging' || github.event.inputs.environment == 'production'
    name: Deploy to Staging
    needs: [build-docker-image]
    uses: ./.github/workflows/infrastructure-server-deploy.yml
    with:
      environment: staging
      external_port: 8500
      project_name: "DFWeb.FR.BootStrap"
      image_name: ${{ needs.build-docker-image.outputs.docker_image_name }}
      config_path: "~/dfweb-config/"
    secrets: inherit

  staging-automated-tests:
    if: github.event.pull_request.merged == true || github.event.inputs.environment == 'staging' || github.event.inputs.environment == 'production'
    name: Run Automated Tests
    needs: [staging]
    uses: ./.github/workflows/infrastructure-automated-tests.yml
    with:
      project_name: "DFAutomatedTests"
      project_path: "DFAutomatedTests"
      config_path: "DFWeb.BE"
    secrets: inherit

  production:
    if: github.event.pull_request.merged == true || github.event.inputs.environment == 'production' || github.event_name == 'release'
    name: Deploy to Production
    needs: [staging-automated-tests]
    uses: ./.github/workflows/infrastructure-server-deploy.yml
    with:
      environment: production
      external_port: 9500
      project_name: "DFWeb.FR.BootStrap"
      image_name: ${{ needs.build-docker-image.outputs.docker_image_name }}
      config_path: "~/dfweb-config/"
    secrets: inherit
