name: DarkFactor Web Back-end - CI Docker Container

on:
  push:
  workflow_dispatch:

env:
  IMAGE_NAME: darkfactorwebimage

jobs:
  build:
    name: Build Docker Image
    uses: .github/workflows/infrastructure-server-ci.yml
    with:
      project_path: "DFWeb.FR.Bootstrap"
      project_name: "DFWeb.FR.Bootstrap"
    secrets: inherit